import Head from 'next/head'
import Image from 'next/image'
import { Box, Text, Heading, Container, Button, Card, CardBody, CardHeader } from '@chakra-ui/react'


export default function TopOppsSummary() {
    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box 
            align-items= "center"
            padding="5rem 2rem 0 2rem"
            className="bg-[#6BCDE7] m-0 p-0 h-screen"
          >
            <Text fontSize="xl" color="brand.darkblue">Hey, we know you need self care...</Text>
            <Box py={10}>
                <Text fontSize="2xl" color="brand.darkpink">but you did</Text>
                <Text fontSize="4xl" color="brand.darkpink"><b>3 OOPS</b></Text>
            </Box>
            <Box>
            <Card direction={{ base: 'row', sm: 'row' }} my={3}
                    overflow='hidden'
                    variant='outline'
                    backgroundColor="#F35057"
                >
                    <CardBody fontWeight="bold" textAlign="Center">
                        <Text size='md' fontSize='2xl' color="white" >RM 83.40</Text>
                        <Text size='md' fontSize='xl' color="white">Shopee</Text>
                    </CardBody>
                </Card>
                <Card direction={{ base: 'row', sm: 'row' }} my={3}
                    overflow='hidden'
                    variant='outline'
                    backgroundColor="#F35057"
                >
                    <CardBody fontWeight="bold" textAlign="Center">
                        <Text size='md' fontSize='2xl' color="white" >RM 255.00</Text>
                        <Text size='md' fontSize='xl' color="white">Shopee</Text>
                    </CardBody>
                </Card>
                <Card direction={{ base: 'row', sm: 'row' }} my={3}
                    overflow='hidden'
                    variant='outline'
                    backgroundColor="#F35057"
                >
                    <CardBody fontWeight="bold" textAlign="Center">
                        <Text size='md' fontSize='2xl' color="white" >RM 43.10</Text>
                        <Text size='md' fontSize='xl' color="white">Lobster & Burger </Text>
                    </CardBody>
                </Card>
            </Box>
          </Box>
        </>
      )

}