import Head from 'next/head'
import Image from 'next/image'
import { Box, Text, Heading, Container, Button, Card, CardBody, CardHeader } from '@chakra-ui/react'


export default function TopOppsSummary() {
    return (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Box 
            align-items= "center"
            padding="5rem 2rem 0 2rem"
            className="bg-[#6BCDE7] m-0 p-0 h-screen"
          >
            <Heading as="h1" size="2xl" color="#5452C6">
              Last Week,<br></br> Your Spend
            </Heading>
            <Heading as="h1" color="brand.darkpink" fontSize='5xl' /*textAlign="center"*/ padding="2rem 0 0 0">RM1300.50</Heading>
            <Box>
              <Heading as="h2" size="lg" pt="2rem" pb="2rem" color="#5452C6">
                Top Categories
              </Heading>

            </Box>
          </Box>
        </>
      )

}