import Head from "next/head";
import Link from "next/link";
import NextButton from "../components/NextButton";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ZEE BY RHB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen px-12 py-10 h-screen bg-cyan-400'>
      {/* <Image src={logo} alt="image" /> */}
        <div className="text-left py-10">
          <p className="text-pink-500 text-4xl py-5 md:text-2xl max-w-xl mx-auto font-bold tracking-wider leading-normal">
            A unique expense management experience for the young boss like you
          </p>
        </div>

        <div className='pb-12'>
          <Link href='/onboarding/ActionGoalIncome'>
            <NextButton text='Create my budget now' />
          </Link>
        </div>
      </main>
    </div>
  );
}
