import Head from 'next/head'
import Image from 'next/image'

const summarySix = () => {
    return (
        <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <div className="text-center py-10">
                <h2 className="text-5xl py-2 text-gray-800 font-medium md:text-6xl">Summary of the week</h2> 
                <div className="flex justify-center">
                <div className='pt-20'>
                    <div className="flex justify-between mb-1 w-96">
                    <span className="text-base font-medium text-gray-800 items-center">RM0</span>
                    <span className="text-base font-medium text-gray-800 items-center">RM1500</span>
                    <span className="text-base font-medium text-gray-800 items-center">RM3000</span>
                    </div>
                    <div className="w-4/5 bg-gray-200 rounded-full h-2.5">
                    <div className="bg-blue-600 h-2.5 rounded-full"></div>
                    </div> 
                
                    <div className="w-full max-w-md p-4 mt-20 bg-white border rounded-lg shadow-md sm:p-8">
                        <div className="flex items-center justify-between mb-4">
                            <p className="text-xl font-bold leading-none text-gray-900">Total Expenses</p>
                            <p className="text-sm font-bold text-gray-900 hover:underline">RM 3278</p>
                        </div>
                    <div>
                            <ul role="list" className="divide-y divide-gray-200 dark:divide-gray-700">
                                <li className="py-3 sm:py-4">
                                    <div className="flex items-center space-x-4">
                                        <div className="flex-shrink-0">
                                        <p className="text-center mx-1">📜</p>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <p className="text-sm font-medium text-gray-900 truncate  ">
                                                Bills
                                            </p>
                                            <p className="text-sm text-gray-500 truncate">
                                                electricity, gas, and internet
                                            </p>
                                        </div>
                                        <div className="inline-flex items-center text-base font-semibold text-gray-900  ">
                                                RM 351
                                        </div>
                                    </div>
                                </li>
                                <li className="py-3 sm:py-4">
                                    <div className="flex items-center space-x-4">
                                        <div className="flex-shrink-0">
                                            <p className="text-center mx-1">🎥</p>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <p className="text-sm font-medium text-gray-900 truncate  ">
                                                Entertainment
                                            </p>
                                            <p className="text-sm text-gray-500 truncate">
                                                movies, music, and sports
                                            </p>
                                        </div>
                                        <div className="inline-flex items-center text-base font-semibold text-gray-900  ">
                                            RM 1960
                                        </div>
                                    </div>
                                </li>
                                <li className="py-3 sm:py-4">
                                    <div className="flex items-center space-x-4">
                                        <div className="flex-shrink-0">
                                            <p className="text-center mx-1">🍔</p>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <p className="text-sm font-medium text-gray-900 truncate  ">
                                                Eating out
                                            </p>
                                            <p className="text-sm text-gray-500 truncate">
                                                fruits, vegetables, and soda
                                            </p>
                                        </div>
                                        <div className="inline-flex items-center text-base font-semibold text-gray-900  ">
                                            RM 4672
                                        </div>
                                    </div>
                                </li>
                                <li className="py-3 sm:py-4">
                                    <div className="flex items-center space-x-4">
                                        <div className="flex-shrink-0">
                                            <p className="text-center mx-1">🚗</p>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <p className="text-sm font-medium text-gray-900 truncate  ">
                                                Transport
                                            </p>
                                            <p className="text-sm text-gray-500 truncate">
                                                car, train, or plane
                                            </p>
                                        </div>
                                        <div className="inline-flex items-center text-base font-semibold text-gray-900 ">
                                            RM 2506
                                        </div>
                                    </div>
                                </li>
                                <li className="pt-3 pb-0 sm:pt-4">
                                    <div className="flex items-center space-x-4">
                                        <div className="flex-shrink-0">
                                            <p className="text-center mx-1">🛍️</p>
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <p className="text-sm font-medium text-gray-900 truncate  ">
                                                Shopping
                                            </p>
                                            <p className="text-sm text-gray-500 truncate">
                                                store, market, or online
                                            </p>
                                        </div>
                                        <div className="inline-flex items-center text-base font-semibold text-gray-900  ">
                                            RM 2367
                                        </div>
                                    </div>
                                </li>
                            </ul>
                    </div>
                    </div>
                </div> 
                </div>                      
        </div>
        </main>
        </div>
    )
}

export default summarySix;
