import Head from 'next/head'
import Image from 'next/image'

const summarySix = () => {
    return (
        <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <div className="text-center py-10">
            <h2 className="text-5xl py-2 text-gray-800 font-medium md:text-6xl">Summary of the week</h2> 
            <div className="flex justify-center mt-20">
            <div>
                <div>
                    <h3 className="text-gray-800">Necessities</h3>
                    <div className="flex justify-between mb-1">
                        <span className="text-base font-medium text-gray-800 items-center pr-6 md:pr-20">RM0</span>
                        <span className="text-base font-medium text-gray-800 items-center px-6 md:px-20">RM1500</span>
                        <span className="text-base font-medium text-gray-800 items-center pl-6 md:pl-20">RM3000</span>
                    </div>
                    <div className="bg-gray-200 rounded-full h-2.5">
                        <div className="w-3/4 bg-blue-600 h-2.5 rounded-full"></div>
                    </div>                            
                </div> 
                <div>
                    <h3 className="text-gray-800">Wants</h3>
                    <div className="flex justify-between mb-1">
                        <span className="text-base font-medium text-gray-800 items-center pr-6 md:pr-20">RM0</span>
                        <span className="text-base font-medium text-gray-800 items-center px-6 md:px-20">RM1500</span>
                        <span className="text-base font-medium text-gray-800 items-center pl-6 md:pl-20">RM3000</span>
                    </div>
                    <div className="bg-gray-200 rounded-full h-2.5">
                        <div className="w-2/4 bg-blue-600 h-2.5 rounded-full"></div>
                    </div>                            
                </div> 
                <div>
                    <h3 className="text-gray-800">Savings</h3>
                        <div className="flex justify-between mb-1">
                        <span className="text-base font-medium text-gray-800 items-center pr-6 md:pr-20">RM0</span>
                        <span className="text-base font-medium text-gray-800 items-center px-6 md:px-20">RM1500</span>
                        <span className="text-base font-medium text-gray-800 items-center pl-6 md:pl-20">RM3000</span>
                    </div>
                    <div className="bg-gray-200 rounded-full h-2.5">
                        <div className="w-1/4 bg-blue-600 h-2.5 rounded-full"></div>
                    </div>                            
                </div> 
            </div>
            </div>
        </div> 
        </main>
        </div>
    )
}

export default summarySix;
