import React from "react";
import Head from "next/head";
import {
  Flex,
  Image,
  Text,
  Button,
  HStack,
  Box,
  Heading,
} from "@chakra-ui/react";
import { useState } from "react";
import Carousel from "framer-motion-carousel";

const colors = ["#f90", "#ef0", "#e0f"];

function SummaryTen() {
  const [number, setNumber] = useState();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        align-items="center"
        padding="5rem 2rem 0 2rem"
        className="bg-[#6BCDE7] m-0 p-0 h-screen"
      >
        <Text fontSize="xl" color="brand.darkblue">
          We can always improve on ourselves{" "}
        </Text>

        <Text fontSize="xl" className="text-[#E044C4]">
          Here are some recommendations for you to ✨be better ✨
        </Text>

        <div style={{ width: 300, height: 200 }}>
          <Carousel>
            {colors.map((item, i) => (
              <div
                key={i}
                style={{
                  width: "100%",
                  height: "100%",
                  backgroundColor: colors[i],
                }}
              ></div>
            ))}
          </Carousel>
        </div>
      </Box>
    </div>
  );
}

export default SummaryTen;
