import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

const summaryFour = () => {
    return (
        <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
        <div className="text-center py-10">
              <h2 className="text-5xl py-2 text-gray-800 font-medium md:text-6xl">Goal Status</h2>
              <h3 className="text-2xl py-2 md:text-3xl text-gray-800">
                Process bar
              </h3>            
            </div>
        </main>
        </div>
    )
}

export default summaryFour;
