import Head from 'next/head'
import Image from 'next/image'

const summaryThree = () => {
    return (
        <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <div className="text-center py-10">
              <h2 className="text-5xl py-2 text-gray-800 font-medium md:text-6xl">But still below budget</h2> 
              <div className="flex justify-center">
                <div className='pt-20'>
                  <div className="flex justify-between mb-1 w-96">
                  <span className="text-base font-medium text-gray-800 items-center">RM0</span>
                  <span className="text-base font-medium text-gray-800 items-center">RM1500</span>
                  <span className="text-base font-medium text-gray-800 items-center">RM3000</span>
                  </div>
                  <div className="w-4/5 bg-gray-200 rounded-full h-2.5">
                    <div className="bg-blue-600 h-2.5 rounded-full"></div>
                  </div> 
                </div> 
              </div>                      
        </div>
        </main>
        </div>
    )
}

export default summaryThree;
